### ISSUE TITLE
Non-standard gulp-file structure not handled properly(?)

### ISSUE THREAD

**Issue by MattTheVV** [psalaets/gulp-src-viewer#4]
For my project the output of me following the readme steps (gulp gsv) is a (not yet instanced) template page in the browser:

    <div class="main" ng-controller="MainCtrl">
        <section class="column">
          <h2>Globs</h2>

          <span ng-if="gulpVersion">
            Local gulp version: <a href="{{gulpVersion | gulpDocsUrl}}">{{gulpVersion}}</a>
          </span>

          <pattern-inputs on-pattern-change="handlePatternChange(patterns)"></pattern-inputs>
        </section>

        <section class="column">
          <h2>Files <i ng-show="loadingFiles" class="fa fa-spinner fa-pulse"></i></h2>

          <selection-breakdown breakdown="selectionBreakdown"></selection-breakdown>

          <ul>
            <li ng-repeat="file in files">
              <div class="file" ng-class="{selected: file.selected}">
                {{file.path}}
              </div>
            </li>
          </ul>
        </section>

        <section class="column">
          <h2>Code</h2>

          <code-box patterns="patterns"></code-box>
        </section>
      </div>

My gulpfile.js file is a reference file, which I'd assume to be the underlying cause.

    require('require-dir')('build/tasks')'

How'd I go about fixing this or is this expected behavior and am I forgetting something?

**Comment by psalaets** [comment]
Hmm that's odd. When the browser shows the template, are there any errors in the devtools console?

**Comment by MattTheVV** [comment]
Behaviour stopped when I upgraded to Gulp4, works nicely now. Thanks.
